# Generated by Django 3.2.4 on 2021-07-18 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=15, null=True)),
                ('parent_address', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LRN', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('middle_initial', models.CharField(max_length=1, null=True)),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('division', models.CharField(max_length=15, null=True)),
                ('school', models.CharField(max_length=15, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('town', models.CharField(max_length=15, null=True)),
                ('date_of_entrance', models.DateField(null=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.parent')),
            ],
        ),
    ]
