# Generated by Django 3.2.4 on 2021-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=15, null=True)),
                ('school', models.CharField(max_length=15, null=True)),
                ('school_days_count', models.IntegerField(null=True)),
                ('school_days_absent_count', models.IntegerField(null=True)),
                ('cause_of_absence', models.CharField(max_length=16, null=True)),
                ('school_days_tardiness_count', models.IntegerField(null=True)),
                ('cause_of_tardiness', models.IntegerField(max_length=16, null=True)),
                ('school_days_present_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_area', models.CharField(max_length=15, null=True)),
                ('first_grading_rating', models.IntegerField(null=True)),
                ('second_grading_rating', models.IntegerField(null=True)),
                ('third_grading_rating', models.IntegerField(null=True)),
                ('fourth_grading_rating', models.IntegerField(null=True)),
                ('remarks', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
